### ISSUE TITLE
Workaround for lost 2to3 support

### ISSUE THREAD

**Issue by rsiverd** [larrybradley/lacosmic#10]
Thanks for your continued work on this project and sorry in advance for reporting what I'm sure is a known issue. Hopefully this workaround is useful for someone.

I have been using lacosmic in a project and recently ran into an issue attempting to install lacosmic in a fresh conda environment with modern conda. In short, the latest setuptools (version >= 58) has explicitly dropped support for use_2to3 which breaks the install. The setuptools changelog indicates the breaking change from September:
[https://setuptools.pypa.io/en/latest/history.html#v58-0-0](url)

I've attached [terminal output](https://github.com/larrybradley/lacosmic/files/7623042/pip_failure.txt) from the install failure for reference but the key piece is:
```error in lacosmic setup command: use_2to3 is invalid.```

I came up with a silly workaround that I thought I'd share that may help folks prior to the next release. Effectively, I create a dummy environment and deliberately downgrade setuptools. This allows lacosmic to install and importantly, caches the wheel so that it can be installed in a different environment with current setuptools.

To install lacosmic, cache the wheel, and destroy the dummy environment:
$ conda create -n dummy python=3.7 anaconda
$ conda activate dummy
$ pip install setuptools==52.0.0     # need version <58 to install lacosmic
$ pip install lacosmic --no-deps
$ conda deactivate
$ conda env remove -n dummy

Now, you can install lacosmic from cache into a new environment (or an existing one) without the risk of setuptools changes:
$ conda create -n useful python=3.7 anaconda
$ conda activate useful
$ pip install lacosmic --no-deps       # this still works with setuptools==58.0.4 using cached wheel

I hope this helps.

**Comment by larrybradley** [comment]
I've released version 1.0.0 that will fix this issue (https://pypi.org/project/lacosmic/1.0.0/).
